const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const core=require('./jht-core');
const babel=require(process.env.JHT_BABEL_PATH || '@babel/standalone');
const {chromium}=require('playwright');
const asset=(file,pkg)=>process.env.JHT_TEST_ASSETS?path.join(process.env.JHT_TEST_ASSETS,file):path.join(path.dirname(require.resolve(pkg+'/package.json')),'umd',pkg+'.development.js');
async function run(){
  assert.equal(core.localDate(new Date(2026,8,11,0,30)),'2026-09-11');
  assert.equal(core.weekday('2026-09-11'),'금');
  const base={students:[{id:'a',note:'old'},{id:'b',note:'old'}]};
  const local=structuredClone(base),remote=structuredClone(base);
  local.students[0].note='local';remote.students[1].note='remote';
  assert.deepEqual(core.merge(base,local,remote),{students:[{id:'a',note:'local'},{id:'b',note:'remote'}]});
  remote.students[0].note='conflict';assert.throws(()=>core.merge(base,local,remote));
  assert.throws(()=>core.merge(base,{students:[]},remote));
  const students=[{id:'a',name:'동명',code:'1111'},{id:'b',name:'동명',code:'2222'}];
  assert.equal(core.pastePlan('동명\t내용',students).errors.length,1);
  assert.equal(core.pastePlan('1111\t쉼표, 유지',students).rows[0].content,'쉼표, 유지');
  assert.equal(core.pastePlan('1111\tA\n1111\tB',students).errors.length,1);
  assert.throws(()=>core.checkCodes({classes:{a:{students:[{code:'1'},{code:'1'}]}}}));
  core.checkCodes({classes:{a:{students:[{code:''},{code:''}]}}});
  const browser=await chromium.launch({executablePath:process.env.JHT_BROWSER_PATH || undefined,headless:true});
  try{for(const file of ['index.html','go1.html']){
    const html=fs.readFileSync(path.join(__dirname,file),'utf8');
    const source=html.match(/<script type="text\/babel">([\s\S]*?)<\/script>/)[1];
    const transformed=babel.transform(source,{presets:['react']}).code;
    new vm.Script(transformed);
    const page=await browser.newPage({viewport:{width:390,height:844}});
    const errors=[];page.on('pageerror',e=>errors.push(e.message));
    page.on('dialog',d=>d.accept());
    await page.setContent('<!DOCTYPE html><html><body><div id="root"></div></body></html>');
    await page.addScriptTag({path:asset('react.js','react')});
    await page.addScriptTag({path:asset('react-dom.js','react-dom')});
    await page.addScriptTag({path:path.join(__dirname,'jht-core.js')});
    await page.evaluate(()=>{
      window.__fail=false;window.__writes=0;
      const ref={onSnapshot(fn){window.__snapshot=fn;setTimeout(()=>{window.__remote=structuredClone(window.__seed);fn({exists:true,data:()=>structuredClone(window.__remote)});},0);return ()=>{};}};
      window.firebase={apps:[{}],firestore:()=>({collection:()=>({doc:()=>ref}),runTransaction:async fn=>{if(window.__fail)throw new Error('테스트 연결 끊김');return fn({get:async()=>({exists:true,data:()=>structuredClone(window.__remote)}),set:(_,data)=>{window.__remote=structuredClone(data);window.__writes++;}});}})};
    });
    await page.addScriptTag({content:transformed.replace('ReactDOM.createRoot',`window.__seed=normalize(initialAppData);Object.values(window.__seed.classes).forEach((c,i)=>c.students.forEach((s,j)=>s.code=String(1111+i*100+j)));ReactDOM.createRoot`)});
    await page.getByRole('button',{name:'선생님 관리자',exact:true}).click();
    await page.getByPlaceholder('비밀번호',{exact:true}).fill('1234');
    await page.getByRole('button',{name:'들어가기',exact:true}).click();
    await page.getByPlaceholder('구체적인 관찰 내용을 적어주세요.').fill('작성중');
    page.removeAllListeners('dialog');page.once('dialog',d=>d.dismiss());
    await page.getByRole('button',{name:'기간 관리',exact:true}).click();
    assert.equal(await page.getByPlaceholder('구체적인 관찰 내용을 적어주세요.').inputValue(),'작성중');
    page.on('dialog',d=>d.accept());
    await page.getByRole('button',{name:'기간 관리',exact:true}).click();
    await page.getByRole('button',{name:'기록 관리',exact:true}).click();
    assert.equal(await page.getByPlaceholder('구체적인 관찰 내용을 적어주세요.').inputValue(),'');
    await page.getByRole('button',{name:'일괄 입력 (반 전체)',exact:true}).click();
    await page.getByRole('button',{name:'붙여넣기로 채우기',exact:true}).click();
    await page.locator('textarea').first().fill('1111\t일괄 입력, 쉼표 유지');
    await page.getByRole('button',{name:'적용',exact:true}).click();
    assert.equal(await page.getByPlaceholder('이 기간의 종합 기록을 적어주세요.').first().inputValue(),'일괄 입력, 쉼표 유지');
    await page.waitForTimeout(800);
    assert.equal(await page.evaluate(()=>Object.values(__remote.classes)[0].students[0].termNotes[__remote.currentTermId]),'일괄 입력, 쉼표 유지');
    await page.getByRole('button',{name:'학생 관리',exact:true}).click();
    const codes=page.getByRole('textbox',{name:'열람 코드',exact:true});
    await codes.nth(1).fill('1111');await codes.nth(1).blur();
    assert.equal(await codes.nth(1).inputValue(),'1112');
    await page.getByRole('textbox',{name:'학생 검색',exact:true}).fill('1111');
    assert.equal(await codes.count(),1);
    const numbers=page.locator('input[type=number]');await numbers.first().fill('83');await numbers.first().blur();
    await page.waitForTimeout(800);
    assert.equal(await page.evaluate(()=>Object.values(__remote.classes)[0].students[0].termMetrics[__remote.currentTermId].homeworkRate),83);
    await page.getByRole('button',{name:'일정 관리',exact:true}).click();
    await page.getByRole('button',{name:'+ 일정 추가',exact:true}).click();
    const date=page.getByLabel('수업 날짜').last();await date.fill('2026-09-11');await date.blur();
    await page.waitForTimeout(800);
    assert.equal(await page.evaluate(()=>Object.values(__remote.classes)[0].schedule.at(-1).day),'금');
    await page.getByRole('button',{name:'기록 관리',exact:true}).click();
    await page.evaluate(()=>window.__fail=true);
    const note=page.locator('textarea').first();await note.fill('실패 후 재시도');
    await page.waitForTimeout(800);
    assert.equal(await page.getByRole('button',{name:'다시 저장',exact:true}).count(),1);
    await page.evaluate(()=>window.__fail=false);
    await page.getByRole('button',{name:'다시 저장',exact:true}).click();await page.waitForTimeout(100);
    assert.equal(await page.evaluate(()=>Object.values(__remote.classes)[0].students[0].termNotes[__remote.currentTermId]),'실패 후 재시도');
    // Independent remote edit is merged while local field changes.
    await page.evaluate(()=>Object.values(__remote.classes)[0].students[1].summary='다른 기기');
    await note.fill('동시 수정 보존');await page.waitForTimeout(800);
    assert.equal(await page.evaluate(()=>Object.values(__remote.classes)[0].students[1].summary),'다른 기기');
    await page.getByRole('button',{name:'← 학부모 화면으로',exact:true}).click();
    await page.getByPlaceholder('학생 코드 입력').fill('1111');
    await page.getByRole('button',{name:'조회',exact:true}).click();
    assert.equal(await page.getByText('동시 수정 보존',{exact:true}).count(),1);
    assert.equal(await page.getByText('83%',{exact:true}).count(),1);
    await page.getByRole('button',{name:'선생님 관리자',exact:true}).click();
    assert.equal(await page.getByPlaceholder('비밀번호',{exact:true}).count(),1);
    await page.getByPlaceholder('비밀번호',{exact:true}).fill('1234');
    await page.getByRole('button',{name:'들어가기',exact:true}).click();
    // Same-field conflict must preserve server value and offer recovery.
    await page.evaluate(()=>Object.values(__remote.classes)[0].students[0].termNotes[__remote.currentTermId]='서버 충돌');
    await note.fill('로컬 충돌');await page.waitForTimeout(800);
    assert.equal(await page.evaluate(()=>Object.values(__remote.classes)[0].students[0].termNotes[__remote.currentTermId]),'서버 충돌');
    assert.equal(await note.inputValue(),'로컬 충돌');
    assert.equal(await page.getByRole('button',{name:'입력 백업 후 최신 내용 불러오기',exact:true}).count(),1);
    assert.deepEqual(errors,[]);
    const fixture=await page.evaluate(()=>__seed);core.validate(fixture);
    assert.throws(()=>core.validate({...fixture,classes:{a:{}}}));
    const duplicate=structuredClone(fixture);Object.values(duplicate.classes)[0].students[1].code='1111';assert.throws(()=>core.validate(duplicate));
    console.log(file+': JSX compilation, parent/admin load, draft navigation, bulk import, duplicate code, search, period metrics, date, save retry, concurrent merge/conflict passed');
    await page.close();
  }}finally{await browser.close();}
  console.log('All tests passed');
}
run().catch(e=>{console.error(e);process.exitCode=1;});
